### ISSUE TITLE
minor bugs in rtkpost

### ISSUE THREAD

**Issue by perboss** [JensReimann/RTKLIB#10]
I notice 2 bugs in rtkpost :
* in "Options" > "Positions" tab, station position file is filtered with wrong extension (atx instead pos). Moreover, the interactive choice does not work on my system, I have to enter manually the file path.
* Still in position tab, when I choose to get Position from file with antenna type and delta-E/N/U read automatically from rinex file, delta-E/N/U is used twice during the processing and one have to correct it.
thanks for your work

**Comment by JensReimann** [comment]
Hi,
and thanks for the bug report.  
Issue #1 is fixed now. The 2nd issue should be addressed to tomojitakasu/RTKLIB directly. I'm not sure if this is an expected feature or a real bug. 

Best regards,
Jens

**Comment by perboss** [comment]
Thanks Jens !
I will ask tomojitakasu.
