### ISSUE TITLE
lRTKLib

### ISSUE THREAD

**Issue by arumrum** [JensReimann/RTKLIB#11]
Hello.. I am very first time using this rtklib
I compiled this program on my Qt 5.9
but it shows some error
cannot find -lRTKLib

Do you know how to remove this error? Thank you

**Comment by arumrum** [comment]
btw, i using Ubuntu 16.04

**Comment by JensReimann** [comment]
That probably means that the sources under /src were not compiled before.

Please run "qmake -recursive" from the top level directory and build all sources (using make) and not just a single application.

**Comment by lukegluke** [comment]
> Please run "qmake -recursive" from the top level directory and build all sources (using make) and not just a single application.

How it can be achieved within qtcreator? Maybe pro files can be corrected somehow?

**Comment by lukegluke** [comment]
Have got same issue on Win10 and Qt 5.9 with shadow building in qtcreator.

I think it would be better to change
`LIBS += -L$${ROOT_DIRECTORY}/lib/ -lRTKLib`
in app.pri to 
LIBS += -L$${OUTPUT_DIRECTORY}/../../lib/ -lRTKLib
for general case.

In fact OUTPUT_DIRECTORY is not used anywhere, so it can be replaced with LIB_DIRECTORY.

**Comment by JensReimann** [comment]
Hi Oleg, 

thank you for the report. I never used shadow builds and hence never faced the problem.

 

Best regards,

Jens

 

Von: Oleg [mailto:notifications@github.com] 
Gesendet: Dienstag, 6. November 2018 12:03
An: JensReimann/RTKLIB
Cc: JensReimann; Comment
Betreff: Re: [JensReimann/RTKLIB] lRTKLib (#11)

 

Have got same issue on Win10 and Qt 5.9 with shadow building in qtcreator.

I think
LIBS += -L$${ROOT_DIRECTORY}/lib/ -lRTKLib
in app.pri should be changed to
LIBS += -L$${OUTPUT_DIRECTORY}/../../lib/ -lRTKLib
for general case.

In fact OUTPUT_DIRECTORY is not used anywhere, so it can be replaced with LIB_DIRECTORY.
