### ISSUE TITLE
Debian package created

### ISSUE THREAD

**Issue by n8ur** [JensReimann/RTKLIB#14]
Hi -- I managed to create a set of Debian packages for rtklib by starting with the distro version (2.4.3b8) and laying your port on top.  With a few edits to the Debian control files, it builds and runs OK, though I am sure that the dependencies list is not correct.

I've built on amd64 and plan to create a set for Raspberry Pi as well.  I'll gladly share these once the but I'm reporting next has been resolved.

**Comment by n8ur** [comment]
I've uploaded Debian packages for 2.4.3b31 to https://febo.com/pages/gps-nuts/rtklib/ with builds for amd64 and armhf (Raspberry Pi).  They are based on Jens' latest code with my patches in config file handling and a bug fix in the rtknavi_qt conf file save dialog (that Jens has also fixed).  I did these for my own use, but feel free to use or ignore them as you like.

**Comment by mfvescovi** [comment]
Hi @n8ur !

FYI: https://packages.debian.org/source/experimental/rtklib
