### ISSUE TITLE
Trivial bug in rtknavi_qt/navimain.cpp

### ISSUE THREAD

**Issue by n8ur** [JensReimann/RTKLIB#17]
Hi Jens --

The changes to navimain.cpp around the call to rtkplot had a 1 character bug that prevented the call from working.

In this line:
    if (!ExecCmd(cmd + opts, 1) && !ExecCmd(cmd2 + opts, 1) && !ExecCmd(cmd3 + opts, 1))

the first cmd needs to be changed to cmd1 or else the call relying on the user's path will fail.  
Fixed with:

    if (!ExecCmd(cmd1 + opts, 1) && !ExecCmd(cmd2 + opts, 1) && !ExecCmd(cmd3 + opts, 1))

**Comment by JensReimann** [comment]
Thanks. I committed the fix.
