### ISSUE TITLE
My updates

### ISSUE THREAD

**Issue by n8ur** [JensReimann/RTKLIB#18]
Hi Jens --
I made a patch of all my changes against your latest commit.  In order to keep the size reasonable I diff'd only the app/ and src/ directories; there was lots and lots of stuff in test/ and especially utilities that I suspect came from the original Debian source.  I don't think any of my changes touch anything other than app/ and src/.  I still don't know why so many files changed even in those directories; I suspect they were changes made in the original Debian packaging.  I think the substantive changes I've made are:

1.  Add -DLINUX to all the makefiles.

2.  Change the inifile handling for both the command line and _qt programs based on the #ifdef LINUX directive.

3.  Change the rtklib_gm.htm file into app/appcmn_qt/gm_template.h and modify gmview.cpp to use that.  This involved a change to rtkplot_qt.pro to add gm_template.h to the build.  (I'd really like to remove all the .htm files from the tree now that they aren't be used, but I'm not sure if that complicates things upstream.)

John

[n8ur-6May2019.patch.zip](https://github.com/JensReimann/RTKLIB/files/3149858/n8ur-6May2019.patch.zip)

**Comment by JensReimann** [comment]
How did you generated the patch? You can't see anything: the first part of the patch removes nearly everything and than adds it all again. I can't see what you actually have touched.

**Comment by n8ur** [comment]
Sorry about that.  My starting point was the Debian 2.4.3b8 source tree, and I think Debianization added a lot of stuff.  I tried to tune diff to remove as much as possible, but obviously too much remained.  Let me run the changes against your source tree.

There weren't that many files changed:
1.  The makefiles and RTKLib.pri to add the "LINUX" flag
2.  app/rtkplot/rtkplot.pri to include gm_template.h in the build
3.  All the *main.cpp files in app/ to apply the config file changes
4.  app/appcmn_qt -- added gm_template.h and modified gmview.cpp for google map template
5.  Added the README-Config.txt file

But stand by and I'll try to get a more useful patchfile to you.

**Comment by n8ur** [comment]
OK, I think I was able to make a diff showing only my changed files against your tree.  I had to hand-prune to do it, so it's possible I may have missed a file or two, most likely some makefiles buried in src/, test/, or utils/.  The change to those would just be adding the "DLINUX" flag.
[RTKLIB-n8ur-patch.zip](https://github.com/JensReimann/RTKLIB/files/3169211/RTKLIB-n8ur-patch.zip)

**Comment by n8ur** [comment]
Jens, could you provide me with your email address?  Mine is jra at febo dot com.  I would like to get a conversation going with you and Gurkan Myczko, the Debian rtklib maintainer, on how to keep the Debian packages in sync with your changes.  It's my fault, but right now there are three slightly different versions of the same code floating around, and I'd like to get away from that.  A three-way conversation should resolve it pretty quickly, I think.

Thanks!

**Comment by mfvescovi** [comment]
John wrote:
> Hi Jens --
> I made a patch of all my changes against your latest commit. In order to keep the size reasonable I diff'd only the app/ and src/ directories; there was lots and lots of stuff in test/ and especially utilities that I suspect came from the original Debian source. I don't think any of my changes touch anything other than app/ and src/. I still don't know why so many files changed even in those directories; I suspect they were changes made in the original Debian packaging. I think the substantive changes I've made are:
> 
>     1. Add -DLINUX to all the makefiles.
> 
>     2. Change the inifile handling for both the command line and _qt programs based on the #ifdef LINUX directive.
> 
>     3. Change the rtklib_gm.htm file into app/appcmn_qt/gm_template.h and modify gmview.cpp to use that.  This involved a change to rtkplot_qt.pro to add gm_template.h to the build.  (I'd really like to remove all the .htm files from the tree now that they aren't be used, but I'm not sure if that complicates things upstream.)

Hi @n8ur !
Please feel free to test Debian rtklib package in experimental suite based on b33.
I stepped in as the new Debian maintainer since Alex has lost personal interest in it.
@JensReimann hasn't yet merged the b34 code base on his repo (see #26), but once it will I'll update the package accordingly.
Upstream release b34 is actually FTBFS (see https://github.com/tomojitakasu/RTKLIB/issues/602) so we need to wait for a fix... but patches are always welcome ;-)
