### ISSUE TITLE
Qt pro files

### ISSUE THREAD

**Issue by DavidKelleySCSC** [JensReimann/RTKLIB#19]
Jens, perhaps a dumb question but here goes...   I thought I would find a download with a Qt *.pro files from your work I could feed to my Qt 5.9 environment and quick jump into this. But not such luck, do not seem to find any make files,  I think I am missing something simple, help.

**Comment by JensReimann** [comment]
Please have a look at the rtklib-2.4.3 branch (master is not converted to use Qt). You'll find the *.pro files there. To generate makefiles, you have to run qmake --recursive
