### ISSUE TITLE
rtkplot_qt in macos 10.14.5 can't change plot font

### ISSUE THREAD

**Issue by YanqingHou** [JensReimann/RTKLIB#22]

**Comment by YanqingHou** [comment]
Hi Jens,
Thanks for provide rtkplot_qt. I compiled it in macOS, and it has the basic function I need: fast-check the result. 
However, there are a few questions:
1. the font size can't be changed. when I selected a font size, and press OK, it doesn't change anything;
2. the zoom function behave strangely.
Do you have any suggestion to revise some code? 
Thanks very much!

**Comment by YanqingHou** [comment]
I added one line:    FontOpt=dialog.selectedFont();
in plotopt.cpp, line 273, just before  dialog.setCurrentFont(FontOpt);
and now it works!

**Comment by JensReimann** [comment]
Thanks for finding this issue. I will include your fix in the source tree.

**Comment by YanqingHou** [comment]
Sorry, but I found this didn't solve the font size problem. 
Now I changed back to your original code, and updated my Qt version. Now the problem solved!
So please don't change your code. 
Thanks.
