### ISSUE TITLE
Sync with official 2.4.3-b34 release?

### ISSUE THREAD

**Issue by mfvescovi** [JensReimann/RTKLIB#26]
Hi Jens!

Any chance you could sync your repository with Tomoji's for core code?
I'm officially packaging RTKLIB for Debian to b33 at the moment, but jumping to b34 would be great.

Thanks in advance for your efforts on this issue.

**Comment by JensReimann** [comment]
Dear Matteo,
the code has been updated. 
The changes have been much larger than for other update of Tomoji and took me much longer to finish. Testing the update is welcome.

**Comment by mfvescovi** [comment]
Hi Jens!

I've tested the new release and it fails:

```
cc -c -Wall -O3 -ansi -pedantic -Wno-unused-but-set-variable -I../../../../src -DENAGLO -DENAGAL -DENAQZS -DENACMP -DENAIRN -DTRACE -DNFREQ=5 -DNEXOBS=3 -DSVR_REUSEADDR  -g ../../../../src/rcv/septentrio.c
../../../../src/rcv/septentrio.c:42:1: error: version control conflict marker in file
   42 | <<<<<<< HEAD
      | ^~~~~~~
../../../../src/rcv/septentrio.c: In function ‘sbf_checksum’:
../../../../src/rcv/septentrio.c:182:1: error: version control conflict marker in file
  182 | =======
      | ^~~~~~~
```

This seems to be caused by some merge conflict headers you left in the code while merging the massive changes made by Tomoji ;-)

Hope this helps.

**Comment by JensReimann** [comment]
Yes, it helps. My previous commit wasn't complete. 
Please try again.

**Comment by mfvescovi** [comment]
Hi!

OK, now the problem is in Tomoji's code, as reported at [#602](https://github.com/tomojitakasu/RTKLIB/issues/602) back in April.
In fact, it fails at:
```
dh_auto_build -Dutil/rnx2rtcm
	cd util/rnx2rtcm && make -j4 "INSTALL=install --strip-program=true"
make[2]: Entering directory '/<<PKGBUILDDIR>>/util/rnx2rtcm'
cc -c -Wall -O3 -ansi -pedantic -I../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 -DNEXOBS=3 rnx2rtcm.c
cc -c -Wall -O3 -ansi -pedantic -I../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 -DNEXOBS=3 ../../src/rtkcmn.c
cc -c -Wall -O3 -ansi -pedantic -I../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 -DNEXOBS=3 ../../src/rinex.c
cc -c -Wall -O3 -ansi -pedantic -I../../src -DTRACE -DENAGLO -DENAGAL -DENAQZS -DNFREQ=3 -DNEXOBS=3 ../../src/rtcm.c
rnx2rtcm.c: In function ‘gen_rtcm_obs’:
rnx2rtcm.c:64:14: error: too few arguments to function ‘gen_rtcm3’
   64 |         if (!gen_rtcm3(rtcm,type[i],i!=j)) continue;
      |              ^~~~~~~~~
```

Let's hope Tomoji will fix it sooner than later ;-)
