### ISSUE TITLE
issue with ToPoint method in graph.cpp

### ISSUE THREAD

**Issue by alexngi66** [JensReimann/RTKLIB#28]
There seems to be an issue with the translation to qt:
In the Tomoji implementation, it was:
int TGraph::ToPoint(double x, double y, TPoint &p)
{
	const double xt=0.1;
	**x=X+(Width-1)/2.0+(x-XCent)/XScale;
	y=Y+(Height-1)/2.0-(y-YCent)/YScale;**
	p.x=(int)floor(x+0.5); p.y=(int)floor(y+0.5);
	return X-xt<x&&x<X+Width-1+xt&&Y-xt<y&&y<Y+Height-1+xt;
}

Note that there is a x on the right side of the assignment and this is causing some plotting issues.

the x and y values need to be returned to work properly instead of being protected by the const in the method declaration.

Thanks for the great work and maintenance that you are doing.

**Comment by JensReimann** [comment]
Thanks for pointing out the issue. It should be fixed by the latest commit
