### ISSUE TITLE
How to build under Linux

### ISSUE THREAD

**Issue by kikislater** [JensReimann/RTKLIB#3]
Hi nice idea to port to QT,

I want to try Qt port on Rtklib under Linux.
How can I simply build it.

What I do : 
- In app folder just running make
- openning RTKlib.pro with qtcreator and tried to compile it but without success
- resulting usage of qtcreator, it generate for example a Makefile in rtkplot_qt. I run make in this folder with no success

Could you tell how to compile it please,

Sincerely,

Sylvain

**Comment by JensReimann** [comment]
There are qmake project files (*.pro) in top level and every subdirectory. Best go to your top level directory and type "qmake -recursive" (sometimes also "qmake-qt5") which generates the makefiles. Then you can run "make". qtcreator does the same. 
Of cause you will need the developer packages of Qt from your linux distribution. If you have any errors while compiling please let me know.

Best regards,
Jens

**Comment by kikislater** [comment]
Waohhh ! 
Amazing, this do the tricks !

![screenshot_20161008_150451](https://cloud.githubusercontent.com/assets/13238064/19213300/c835db20-8d68-11e6-951b-54f095191596.png)

Thank you for porting it to QT

**Comment by kikislater** [comment]
I just have an error with google earth plugin

**Comment by JensReimann** [comment]
Yes, you would need the Google Earth Plugin which is currently not supported under Linux. Sorry and blame Google.
There are alternatives like Cesium (http://cesiumjs.org/), but this would require a lot of effort to support.

**Comment by kikislater** [comment]
Thank you, yes I know cesium.
Don't care about google earth plugin

**Comment by ghost** [comment]
If somebody wants Windows binary of RTKLib b26, let me know, and i'll upload it somewhere. Cheers.
