### ISSUE TITLE
QT port for rtkexplorer

### ISSUE THREAD

**Issue by GPSFan** [JensReimann/RTKLIB#4]
Any chance of a new branch to address the improvements that Tim has made in his fork:
https://github.com/rtklibexplorer/RTKLIB
He is changing the windoze code and the /src of RTKLIB to reflect his new api changes, but not the _qt code. I have built your _qt code for several ARM SBC's and it works quite well. I'd love to see the cross platform QT replace the windoze only code.

**Comment by JensReimann** [comment]
I'm aware of the RtklibExplorer branch. I haven't started a branch yet, because I feel merging both - RtklibExplorer und Qt port branch - to Tomoji's code is the way to go. I'm also a bit concerned about the additional work to keep another branch up to date.

BTW: Integrating RtklibExplorer's changes into Qt port should be to hard, if real required.

**Comment by GPSFan** [comment]
Hi Jens,

Thanks for the response,

A single codebase is always preferable. I've never done any real coding 
in QT so I'm a bit unsure of my abilities. I would love to help.

It would be great if there were just one repo with a development branch, 
an experimental branch, and a stable branch. Where the api changes got 
merged as they became stable or dropped if found unnecessary or unwanted.

Tim has made some real improvements in the way the M8T performs as well 
as the ultra low cost M8N. He has wanted to merge them into Tomoji's but 
was unsure of the utility of the M8N updates as they may not be needed 
by hard core RTK users.

On the other hand I think that QT is the way to go for further GUI 
development. Most windoze centric developers don't seem to care about 
other OS's. I am an embedded developer and work primarily with ARM based 
SBC's. I've compiled and run your rtknavi_qt on a pcDuino3 nano, as well 
as a OrangePi One, runs well with low CPU usage using the Armbian distro.


     Thanks for the work you have done porting RTKLIB to QT. It is very 
much appreciated.

    ...ken...

**Comment by JensReimann** [comment]
Have a look to the new rtklibExplorer_2.4.3 branch. It's a quick merge of rtklibExplorer and the qt port.

Have a lot of fun using it,
Jens
