### ISSUE TITLE
NTRIP caster User-ID can't contain @

### ISSUE THREAD

**Issue by GPSFan** [JensReimann/RTKLIB#5]
rtknavi_qt
I am trying to set the NTRIP Caster Host User-ID. My user id for this caster is my e-mail address and when I enter it into the field, it doesn't save to the rtknavi_qt.ini file. The User-ID is truncated at the @ and the password I entered in the field disappears. 
The Windows version of rtknavi behaves properly.
The Qt version using a different caster with a different User-ID not containing @ also behaves properly.
I tried entering the proper UserID:password@host:port/mountpoint in the rtknavi.ini file, but the User-ID comes into the NTRIP Caster dialog truncated at the @.

**Comment by JensReimann** [comment]
Thank for reporting this bug.
It has been fixed in latest rtk_2.4.3 branch.

**Comment by GPSFan** [comment]
Verfied. This is now fixed.
