### ISSUE TITLE
Base Station Monitor does not display RTCM3 decoded packets

### ISSUE THREAD

**Issue by GPSFan** [JensReimann/RTKLIB#6]
rthnavi_qt
When receiving NTRIP RTCM3 data from an NTRIP caster, the monitor display does not decode the RTCM3 packets as does the windows version.
If I switch to HEX or ASCII, I get data displayed in the monitor window.
In the windows version I get:
RTCM 1004 ( 183) xxxxxxxx
RTCM 1012 ( 109) yyyyyyyyyyyyy
RTCM 1032 ( 23) zzz
etc.
If I use a serial interface and get data from a u-blox receiver (for rover or base) , and choose ublox format, the monitor displays ublox packets as does the windows version. 

My fear is that the RTCM3 decoding is not happening in other places as well.
This using the latest 2.4.3 update that does fix my  earlier issue.

**Comment by GPSFan** [comment]
Latest commit fixes this issue. Thanks Jens.....

**Comment by JensReimann** [comment]
The problem was only related to the display of RTCM messages.
